b1 = True
bs = ''
b2 = bool(bs)
print(b1, ' | ', b2, ' = ', b1 | b2)
print(b1, ' & ', b2, ' = ', b1 & b2)
print(b1, ' ^ ', b2, ' = ', b1 ^ b2)
bstr = input('input bool no. (True, False) : ')
b3 = bool(bstr)
print(b1, ' | ', b3, ' = ', b1 | b3)
print(b1, ' & ', b3, ' = ', b1 & b3)
print(b1, ' ^ ', b3, ' = ', b1 ^ b3)
print(b2, ' | ', b3, ' = ', b2 | b3)
print(b2, ' & ', b3, ' = ', b2 & b3)
print(b2, ' ^ ', b3, ' = ', b2 ^ b3)
print('not ', b2, ' = ', not b1)
istr = input('input integer No. : ')
ival = int(istr)
hstr = hex(ival)
bstr = bin(ival)
print(ival, ' => ', hstr, ' => ', bstr)
ch = input('Input a string (first char only use) : ')
cval = ord(ch[0])
sval = chr(cval)
print(ch, ' => ', ch[0], ' => ', cval, ' => ', sval)
